version: '3'

services:

  db:
    image: mysql
    restart: unless-stopped
    container_name: VirtualBookStoreDB
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=treinamentodb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - spring-network
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    container_name: app
    ports:
      - "8080:8080"

networks:
  spring-network:
    driver: bridge